[profile.default]
src = "contracts"
test = "test/foundry"
out = "out"
cache_path = "cache_forge"
libs = ["lib", "node_modules"]
solc_version = "0.8.26"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./" }]

[doc]
out = "docs"
title = "Infrastructure Contracts"
ignore = ["contracts/mocks/*.sol", "contracts/libraries/*.sol", "contracts/test/*.sol"]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 50
fail_on_revert = false

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
